### ISSUE TITLE
May need to handle rate limits

### ISSUE THREAD

**Issue by beachdweller** [kangwonlee/Github-API#8]
## Motivation

* Number of messages may exceed the fixed rate

## Action plan

* Periodically check rate limits
* If getting close to the limit, yield control to other processes

> If you're making a large number of POST, PATCH, PUT, or DELETE requests for a single user or client ID, wait at least **one second** between each request.

## References

* [Rate limit](https://developer.github.com/v3/rate_limit/)
* [Abuse rate limits](https://developer.github.com/v3/#abuse-rate-limits)
* [Best practice guide](https://developer.github.com/v3/guides/best-practices-for-integrators/)
* [Dealing with rate limits](https://developer.github.com/v3/guides/best-practices-for-integrators/#dealing-with-rate-limits)
* [Dealing with abuse rate limits](https://developer.github.com/v3/guides/best-practices-for-integrators/#dealing-with-abuse-rate-limits)

**Comment by kangwonlee** [comment]
* 1e4bd6c implemented *waiting one second*
